# Site settings
title: Matias Verdier | Blog
email: verdier.matias@gmail.com
description: >
  Esta es mi pagina personal donde compartire cosas que me parezcan interesantes,
  mis proyectos y cualquier otra cosa que se me ocurra.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://matiasverdier.github.io" # the base hostname & protocol for your site
twitter_username: matiasvj
github_username:  MatiasVerdier

# Build settings
markdown: kramdown
